### PR TITLE
Split breadcrumb HTML off from h1

### PR DESCRIPTION
**Pull request by tombye**
On pages where we currently put the name of the template or folder in with the path to it, this splits the name off from the path.

Intended to make it less confusing to screen reader users. Full details in the story:

https://trello.com/c/YGxJqotD/991-h1-for-template-or-folder-page-is-confusing-for-screen-readers

image

image

image

### Pages to check

This pattern appears on:
- the templates page at the root and in a folder
- manage folder page
- copy template page
- choose template (as part of the 'respond to inbound message' flow)

### Changes to the page title

Because the h1 was confusing when it contained the path, I also changed the page title because it also contained the path. 

Many other sites, including www.gov.uk, use the 'page - parent page - website' pattern because the parent page gives enough context to tell pages with the same name apart. I used a variation of this which also includes the service.

@karlchillmaid will need to sign off on these changes.

### CODE REVIEW

**Comment by kr8n3r** [comment]
this looks good.

should manage page also have "Nest 1" in this case without a link?
Screenshot 2024-12-06 at 09 52 11

**Comment by kr8n3r** [comment]
i think some padding/margin got lost somewhere

Screenshot 2024-12-06 at 09 58 30
Screenshot 2024-12-06 at 10 00 21

**Comment by tombye** [comment]
> this looks good.
> 
> should manage page also have "Nest 1" in this case without a link? Screenshot 2024-12-06 at 09 52 11

I think so, assuming I understand. Here's a screenshot of what a similar manage folder page looks like currently:

image

**Review by kr8n3r — APPROVED** [review]
happy with the code

**Pull request merged**
