### PR TITLE
Restrict negative values for rate limits

### PR DESCRIPTION
**Pull request by samuelhwilliams**
Not too fussed about the error text (but we can customise it as needed) because it's just a platform admin form. But feels like we should at least stop people being able to enter negative numbers.

image

### CODE REVIEW

**Comment by samuelhwilliams** [comment]
@karlchillmaid if you've got any interest in this error message I'm happy to take some words from you to use for the error message :) It's a platform-admin only form though so no worries if you have better things to do for now.

**Comment by quis** [comment]
Should we also prevent floats while we’re here?

**Comment by karlchillmaid** [comment]
> 

`Number must be equal to or greater than 0`?

**Review by CrystalPea — APPROVED** [review]

**Comment by samuelhwilliams** [comment]
@quis I think we already do?

image

**Review by quis — APPROVED** [review]

**Pull request merged**
