### PR TITLE
Updated Readme.md project setup steps

### PR DESCRIPTION
**Pull request by McCloudA**
I think these updates will help other developers in the future get this going faster.

### CODE REVIEW

**Comment by idavidmcdonald** [comment]
Hi Aaron, many thanks for this! We love external contributions.

There are definitely some improvements (and corrections) in here that are really useful. Some bits I might argue are probably more verbose than they need to be for us. Whilst our code is all open, the README is aimed at developers on our team, for example who are all familiar with Brew and use `n` rather than `nvm`.

I'm going to suggest that I open a new PR based on yours but with a few changes to remove one or two bits that are less relevant to our team and then I could get your thoughts on it? How does that sound?

Out of interest, what got you spinning up our admin app? I know a few countries have forked the code to make their own versions of Notify, is that the case for you too?

Thanks again!

**Comment by McCloudA** [comment]
David,

A new PR based on mine would be great. I tend to be verbose, since (a) I
want other people to set the project up easily, and (b) most engineers
don't leave as much documentation as they should... since it works on their
machine. 😉 I err on the side of caution & clarity.

I'm on a project working with engineers from Twilio and Senzing to create
an app that US officials can use to notify voters during crises and dispel
bad information using SMS, email, and voice messages (audio files). We were
thinking of using your Notify, but I haven't gotten it working yet - I
spent today building my own SMS notification app w/ React, Express, and the
Twilio API.

I'll spend Wed. taking another crack at getting Notify running.

~ Aaron


---
LinkedIn.com/in/AaronMcCloud <https://www.linkedin.com/in/aaronmccloud>
Cell:  (206) 949-9806

*"We are such stuff as dreams are made on, and our little life is rounded
with a sleep."*
~ Prospero
(The Tempest, Act 4 Scene 1)

**Comment by idavidmcdonald** [comment]
Awesome. I've put up a new PR with a new commit on top of yours to to make the README a bit more appropriate for our team. Apart from a few smaller tweaks, the main change is I've removed some of the examples of how to install and use virtualenvwrapper and pyenv but have linked to the original docs as I don't want our readme do to much duplication of those and remain more specific to our project than generally how to manage python projects.

https://github.com/alphagov/notifications-admin/pull/3456

Feel free to take a look through and leave a review/comments if you have any :)

Thanks again, your contribution is much appreciated. I particularly like the numbered list approach for the set up instructions, I feel that really helps with readability.

Your project sounds interesting. If you run into any problems getting applications running then feel free to let us know and we might be able to offer a few bits of advice/troubleshoot. The main other app you'll need to get running is https://github.com/alphagov/notifications-api if you haven't already found it. Just let us know if we can help!

**Comment by McCloudA** [comment]
David,

Thanks for the info! I know I'm a day late, but I like your README.md
update. More concise than mine.
I built my own MVP for sending SMS messages, and will ask you if I have any
more questions re/ Notify.
I had kinda a crazy week this week.

Also, let me know if you're ever in Seattle so we can get drinks.
Once the COVID-19 apocalypse is over.

All the best,
Aaron


---
LinkedIn.com/in/AaronMcCloud <https://www.linkedin.com/in/aaronmccloud>
Cell:  (206) 949-9806

*"We are such stuff as dreams are made on, and our little life is rounded
with a sleep."*
~ Prospero
(The Tempest, Act 4 Scene 1)

**Comment by McCloudA** [comment]
David,

I'd like to use the notifications-api with Twilio, but am running into some
issues. Here are a few of my questions:

*1.* It looks like you're using FireText. I want to integrate with Twilio
instead. To do so it looks like I will need to replace
the FIRETEXT_API_KEY, replane that with the Twilio API key, and change all
references in the app (assuming I don't need to refactor more of the app
code to work with Twilio). Does this sound accurate?

*2.* There do not seem to be integration instructions. Have I
overlooked something in the README.md?

*3.* We are looking to do 2 levels of API integration, pinging a service
called Senzing for entity resolution on uploaded data and then directing
that data into Twilio. This looks like several steps beyond the current
state of the Notify app; I'm leaning towards building my own app., but
would like to hear your thoughts - since you know this repo better than
me. 😉


Thanks a ton!

All the best,
Aaron




---
LinkedIn.com/in/AaronMcCloud <https://www.linkedin.com/in/aaronmccloud>
Cell:  (206) 949-9806

*"We are such stuff as dreams are made on, and our little life is rounded
with a sleep."*
~ Prospero
(The Tempest, Act 4 Scene 1)

**Comment by idavidmcdonald** [comment]
Will do!

1) At a glance, yes, you will need to replace all uses of `firetext` with `twilio`. This will also likely include files that handle the response from the provider, which may return their response in a different format of JSON which you will then need to parse appropriately for Twilio.

2) Could you clarify what you mean by integration please, as in integrated with what?

3) So I can't tell too much but I don't think it's necessarily a bad idea to build something yourself. It will end up being lighter weight then our code, you'll get a good understanding of it by building (potentially in a language you prefer) and it won't include code/features that aren't relevant for you. For example, you may not need
- inbound text messages
- billing and reporting using our model of 'services'
I think if you manage to spin up both the api and admin app locally and play around with the admin app, it will give you a good idea of what the functionality is and how closely this may match what you need. If it turns out you do need something pretty close, you may also be interested to reach out to the Canadian, Singaporian and Australian governments who I believe have all forked the code and run their own versions for more advice on how to do this well and customise it for your needs.

**Comment by McCloudA** [comment]
Integration of the main Notify frontend with the notifications-api backend
repo is what I meant.

Thanks for your quick responses!
I think we're going to build our own app. I think what we want is simpler
than your full app, and it looks like we'll be distributing it as a desktop
app (React/Express/Electron w/ Twilio).

Thanks for all your help. I really appreciate it!

~ Aaron




---
LinkedIn.com/in/AaronMcCloud <https://www.linkedin.com/in/aaronmccloud>
Cell:  (206) 949-9806

*"We are such stuff as dreams are made on, and our little life is rounded
with a sleep."*
~ Prospero
(The Tempest, Act 4 Scene 1)

**Pull request merged**
