### PR TITLE
Precompiled show preview with overlay when validation fails

### PR DESCRIPTION
**Pull request by CrystalPea**
Has to go after this template-preview PR: alphagov/notifications-template-preview#315
And this API PR: https://github.com/alphagov/notifications-api/pull/2437

Part of this story: https://www.pivotaltracker.com/story/show/164798738

#### Screenshots:
cursor on the postage sign:
Screen Shot 2019-04-04 at 11 57 14

cursor not on the postage sign:
Screen Shot 2019-04-04 at 11 57 05

### CODE REVIEW

**Comment by quis** [comment]
Nice work 😎 

Does it show up on the PDF download as well?

**Comment by CrystalPea** [comment]
@quis thanks 😊. It doesn't show on the download for now, should I add that?

**Comment by quis** [comment]
@CrystalPea Yeah, I think that will help people find the problem if their text is a tiny bit into the red.

**Comment by CrystalPea** [comment]
@quis this is done now ☺️ 

 I still need to write some unit tests and hopefully do some refactoring with Leo when I'm back though :)

**Pull request merged**
