### PR TITLE
Enforce order and style of imports

### PR DESCRIPTION
**Pull request by quis**
Done using isort<sup>1</sup>, with the following command:
```
isort -rc ./app ./tests
```

Adds linting to the `run_tests.sh` script to stop badly-sorted imports getting re-introduced.

Chosen style is ‘Vertical Hanging Indent’ with trailing commas, because I think it gives the cleanest diffs, eg:
```python
from third_party import (
    lib1,
    lib2,
    lib3,
)
```
to
```python
from third_party import (
    lib1,
    lib2,
    lib3,
    lib4,
)
```

Gives a diff of:
```diff
+    lib4,
```

1. https://pypi.python.org/pypi/isort

### CODE REVIEW

**Comment by leohemsted** [comment]
i'm hugely in favour of this but we'll need to figure out how to make pycharm follow this or we'll never get it past becca 😉

**Comment by quis** [comment]
Instructions (but no plugin) for PyCharm here: https://github.com/timothycrosley/isort/wiki/isort-Plugins

**Comment by quis** [comment]
To rebase this branch without having to deal with loads of merge conflicts:
```
git fetch
git checkout import-sort
git checkout origin/master -- ./app ./tests
pip install -r requirements_for_test.txt
isort -rc ./app ./tests
git commit -a --amend -C HEAD
git push -f origin import-sort
```

**Comment by quis** [comment]
To rebase simply run:
```shell
git fetch
git checkout import-sort
git reset --hard origin/master
git checkout origin/import-sort -- requirements_for_test.txt scripts/run_tests.sh setup.cfg
isort -rc ./app ./tests 
git commit -a -C 0c660b49
git push -f origin import-sort
```

**Comment by servingUpAces** [comment]
I don't mind as long as the first commit with isort only contains the import diffs and nothing else. I should be able to tell pycharm to follow the same format when organising imports.

**Comment by quis** [comment]
I’m going to merge this now while the only other people with open PRs that it will cause merge conflicts on are mine.

**Pull request merged**
