### PR TITLE
Image optimisation

### PR DESCRIPTION
**Pull request by Nooshu**
Opening a PR to optimise the static images used on Notify. Each of the below sections has a separate commit so can be cherry-picked as required, or can be squashed into one commit if preferred.

## Main folder
| Filename           | Before (KB) | After (KB) | % diff |
|--------------------|-------------|------------|--------|
| cross-grey.png     | 3.88        | 0.82       | -79    |
| envelope-fold.png  | 6.0           | 1.85       | -68    |
| notify-diagram.png | 48.0          | 32.0         | -34    |
| preview_error.png  | 17.0          | 6.0          | -64    |
| tick-black.png     | 4.0           | 0.42       | -90    |
| tick-white.png     | 0.62        | 0.42       | -33    |
| tick.png           | 0.83        | 0.55       | -34    |
| **Total**              | **80**          | **42**         | **-48**    |

## Email template
| Filename                | Before (KB) | After (KB) | % diff |
|-------------------------|-------------|------------|--------|
| spacer.png              | 0.095       | 0.068      | -28    |
| bis_crest_27px_x2.png   | 4.2         | 2.0        | -52    |
| coastguard_27px_x2.png  | 12.7        | 7.6        | -35    |
| data_gov_uk_x2.png      | 3.3         | 2.2        | -34    |
| hmrc_crest_27px_x2.png  | 4.0         | 2.9        | -26    |
| ho_crest_27px_x2.png    | 8.0         | 4.7        | -41    |
| mod_crest_27px_x2.png   | 7.5         | 4.2        | -44    |
| org_crest_27px_x2.png   | 3.7         | 2.3        | -38    |
| portcullis_27px_x2.png  | 7.3         | 4.2        | -43    |
| so_crest_27px_x2.png    | 8.0         | 5.6        | -28    |
| ukaea_crest_27px_x2.png | 10.0        | 7.0        | -30    |
| ukho_27px_x2.png        | 9.0         | 5.3        | -42    |
| wales_crest_27px_x2.png | 8.2         | 4.5        | -45    |
| **Total**                   | **82.3**        | **56.3**       | **-32**    |

## Letter template
| Filename   | Before (KB) | After (KB) | % diff |
|------------|-------------|------------|--------|
| qr1.png    | 0.4         | 0.28       | -30    |
| type29.png | 1.4         | 1.0        | -26    |
| **Total**      | **1.8**         | **1.28**       | **-29**    |

## Product
| Filename                     | Before (KB) | After (KB) | % diff |
|------------------------------|-------------|------------|--------|
| proposition-illustration.png | 10.0        | 6.0        | -42    |
| team.jpg<sup>†</sup>                    | 97          | 48         | -40    |
| **Total**                        | **107**         | **54**         | **-49**    |

†: Dimensions of this image changed from 960x640 down to 700x467. Upon testing the responsive nature of the page, the maximum width the image came to was 595 pixels (this is at the mobile breakpoint).

## SVG
SVG optimisation using a different method so has been separated out.

| Filename                 | Before (KB) | After (KB) | % diff |
|--------------------------|-------------|------------|--------|
| message-sending-flow.svg<sup>‡</sup> | 40          | 32         | -20    |

‡: These are GZipped sizes which Notify supports and is what is delivered to browsers.

### CODE REVIEW

**Comment by tombye** [comment]
Thanks for this @Nooshu, having a 👀 now.

**Comment by tombye** [comment]
All the new versions of the images look OK to me.

There are a few images I can't find uses for any more so we should probably look at removing them instead:

- https://github.com/alphagov/notifications-admin/blob/master/app/assets/images/email-template/spacer.png (macro that used it was removed in https://github.com/alphagov/notifications-utils/commit/ff6a318bd7228c67e903fb7b3df3376c1c78a253#diff-7d3ef7fa9c747e8e757790bb586383e0)
- https://github.com/alphagov/notifications-admin/blob/master/app/assets/images/notify-diagram.png
- https://github.com/alphagov/notifications-admin/blob/master/app/assets/images/letter-template/qr1.png
- https://github.com/alphagov/notifications-admin/blob/master/app/assets/images/letter-template/type29.png

I think these were used on types of banner we don't use any more:
- https://github.com/alphagov/notifications-admin/blob/master/app/assets/images/tick-black.png
- https://github.com/alphagov/notifications-admin/blob/master/app/assets/images/tick-white.png

@quis would you mind checking I'm not missing any use cases here?

**Comment by quis** [comment]
These files should not be deleted:
- [spacer.png](https://github.com/alphagov/notifications-admin/blob/master/app/assets/images/email-template/spacer.png) – people will still have emails in their inboxes that reference this image, let’s not break those images (and potentially the layout) for them
- [qr1.png](https://github.com/alphagov/notifications-admin/blob/master/app/assets/images/letter-template/qr1.png) – this is [used when rendering previews of templated letters](https://github.com/alphagov/notifications-utils/blob/8a7550ab60a6c5faa2e4a642bb6ec0d03313db9e/notifications_utils/jinja_templates/letter_pdf/_main_css.jinja2#L101)
- [type29.png](https://github.com/alphagov/notifications-admin/blob/master/app/assets/images/letter-template/type29.png) – this is [used when rendering previews of templated letters](https://github.com/alphagov/notifications-utils/blob/8a7550ab60a6c5faa2e4a642bb6ec0d03313db9e/notifications_utils/jinja_templates/letter_pdf/_main_css.jinja2#L91)

These can safely be deleted:
- [notify-diagram.png](https://github.com/alphagov/notifications-admin/blob/master/app/assets/images/notify-diagram.png)
- [tick-black.png](https://github.com/alphagov/notifications-admin/blob/master/app/assets/images/tick-black.png)
- [tick-white.png](https://github.com/alphagov/notifications-admin/blob/master/app/assets/images/tick-white.png)

**Comment by quis** [comment]
@Nooshu thanks for doing this, and for making the pull request message and structure of the commits so clear. Banging piece of work.

**Pull request merged**
