### PR TITLE
Update error messages

### PR DESCRIPTION
**Pull request by karlchillmaid**
This PR updates 2 error messages to include contractions. This is consistent with other error message content.

### CODE REVIEW

**Comment by idavidmcdonald** [comment]
Oh it looks like some test content also contains these strings so you will need to change any references in the 'test' folder

**Comment by karlchillmaid** [comment]
Thanks @idavidmcdonald 

The [plain English guidance](https://www.gov.uk/guidance/content-design/writing-for-gov-uk#plain-english) on GOV.UK says:

>"use contractions like you’ll (but avoid negative contractions like can’t)"

I think this approach comes from GOV.UK’s aim to write in a way that better reflects how our users speak, and to avoid sounding overly formal. It's not a hard and fast rule, though – context plays a part.

In the second of the 2 examples you found, I think `you are` actually works better. In the first, we could use either, although maybe `you’re` reads better aloud. It's pretty subjective stuff, and not a massive problem if we’re not always consistent.

The main reason for changing the wording in this PR is that there didn’t seem to be a good enough reason to use `there is` in these error messages, when we use `there’s` in all the others.

Interestingly the Guardian style guide (which GOV.UK defers to for anything not covered in the A-Z) says:

>"Do not overuse contractions ... while they might make a piece more colloquial or easier to read, they can be an irritant and a distraction, and make a serious article sound frivolous."

🤷‍♂

**Comment by karlchillmaid** [comment]
> Oh it looks like some test content also contains these strings so you will need to change any references in the 'test' folder

I can't find the relevant test files.

**Comment by idavidmcdonald** [comment]
Check out the two last search results in this:
https://github.com/alphagov/notifications-admin/search?q=%22You+are+not%22&unscoped_q=%22You+are+not%22

**Comment by idavidmcdonald** [comment]
Concourse says you have fixed the tests succesfully :) feel free to merge if you are happy

**Pull request merged**
