### PR TITLE
Remove unexpected argument when calling `create_service_template`

### PR DESCRIPTION
**Pull request by klssmith**
This function no longer takes queue type.

### CODE REVIEW

**Comment by idavidmcdonald** [comment]
I haven't looked at the code too much but is it easy for us to add a unit test to this bit of code so we would catch something like this in the future?

Open to not adding one if it isn't easy to test though...

**Review by samuelhwilliams — APPROVED** [review]
Agree it'd be nice to add a test - could be done in a separate followup PR if needed though.

**Comment by klssmith** [comment]
@idavidmcdonald I think a test would definitely be useful, but it didn't look particularly straightforward to add one in - I could merge this then look separately since I'm not sure how long it would take me to write a test.

**Comment by idavidmcdonald** [comment]
I'll leave you to judge Katie, thanks :)

**Review by leohemsted — APPROVED** [review]
oops ignore, was checked out to wrong commit 🤦

**Comment by klssmith** [comment]
Turns out it wasn't really difficult to test this after all, so I've added one here https://github.com/alphagov/notifications-admin/pull/4610

**Pull request merged**
