### PR TITLE
Update upload a letter content

### PR DESCRIPTION
**Pull request by karlchillmaid**
Research shows users:

* are confused about when they would need to upload a letter
* expect an uploaded letter to behave in the same way as a letter template – with placeholders that can be filled
* miss important information about the layout specifications of their letter

This PR updates the _Guidance_ and _Upload a letter_ pages to:

* do a better job of explaining the feature
* provide context, guidance and important information at the right point in the journey

### CODE REVIEW

**Comment by quis** [comment]
I think the blank state of the uploads page needs a bit more work. Happy to help you code it up (it won’t fit in the existing pattern) but we need to get across that:
- there’s nothing here yet
- what uploading letters is
- how you need to go to templates to upload lists of recipients

Thoughts?

**Comment by karlchillmaid** [comment]
@quis If we're going to use the same (or virtually the same) content on the _Guidance_ and _Upload a letter_ pages, is there a smarter way we can manage that content?

**Comment by quis** [comment]
@karlchillmaid we can make a partial, which is code shared between two pages. But I’m not sure it’s worth the added complexity if we’re only sharing the content between two different places, and there might be slight variations.

**Comment by quis** [comment]
This feels strange (I might have messed it up during the rebase though).

It looks like it’s jumping down the page. Should it link straight to the PDF?

ualjmp

**Comment by karlchillmaid** [comment]
@quis Yes. I forgot to update the link.

**Pull request merged**
