### PR TITLE
Add link to Slack channel in footer

### PR DESCRIPTION
**Pull request by quis**
@yahoopete good idea/bad idea?

### CODE REVIEW

**Comment by yahoopete** [comment]
Good idea... wonder if there is a better name than 'Slack' channel ... incase you don't know what that is....

**Comment by quis** [comment]
‘Join the discussion on Slack’ or something like that?

**Comment by mannickutd** [comment]
:+1:

**Comment by quis** [comment]
‘Discuss on Slack’?

**Comment by yahoopete** [comment]
Chat?

**Comment by yahoopete** [comment]
screen shot 2016-04-26 at 11 46 09

**Comment by yahoopete** [comment]
:+1:

**Pull request merged**
