### PR TITLE
Update formatting.html

### PR DESCRIPTION
**Pull request by saimaghafoor**
Update formatting page to include guidance for markdown and what it each component can be used for.

### CODE REVIEW

**Comment by samuelhwilliams** [comment]
I've pulled these changes into https://github.com/alphagov/notifications-admin/pull/4738

**Comment by samuelhwilliams** [comment]
I've taken these changes out of #4738 so we can keep this around. It will need some updating but we can go over that together :)

**Comment by samuelhwilliams** [comment]
@saimaghafoor Here's what this branch looks at for now :)

One thing - I think we need to update 'Formatting' in the sidebar to match the h1 from the page, 'Formatting emails and letters'?

FireShot Capture 001 - Formatting emails and letters – GOV UK Notify - notify localhost

**Comment by samuelhwilliams** [comment]
Did you want to have a go at it or shall we pair? :)

**Comment by saimaghafoor** [comment]
> 

I think defo pair!

**Review by samuelhwilliams — APPROVED** [review]

**Pull request merged**
