### PR TITLE
Move ‘upload recipients’ button

### PR DESCRIPTION
**Pull request by quis**
# Before 

image

image

# After 

image

image

image

### CODE REVIEW

**Comment by yahoopete** [comment]
I like it.

Slightly worried about how to ship it without disrupting... it is intuitive, but user guides.... #discuss

**Comment by quis** [comment]
…and out the teams who’ve sent messages this month, how many distinct users have been doing the uploading?

Number of users uploading files |                        Service name
-------|----------------------------------------------------
5 | School Admissions Buckinghamshire County Council
5 | Her Majesty's Passport Office
5 | Office of the Public Guardian
4 | IAC_Judicial Bookings
4 | ORS Reminder Service
3 | G Cloud Team
3 | Department for Education: Becoming a Teacher
3 | Crown Commercial Service MI Collection
3 | Cafcass
3 | ESFA academy financial returns
2 | Register to Vote
2 | Cash service
2 | Civil Service Local News
2 | Elmbridge Council Tax
2 | ESFA feedback
2 | ESFA pre-16 funding
2 | HM Government Business Engagement
2 | HMPO Southport
2 | Home Office Reporting
2 | MHCLG:   Housing and Planning Data Collection Team
2 | midata in energy
2 | Operational Delivery Profession
2 | Small Claims Mediation Service
2 | Soft Drinks Industry Levy
2 | Tier 4 Premium
2 | Veterans Welfare Service

**Comment by quis** [comment]
# Remove other references to ‘upload recipients’

For consistency:

image

image

image

**Comment by quis** [comment]
Developed further in https://github.com/alphagov/notifications-admin/pull/2207

**Pull request closed without merging**
