### PR TITLE
Add new free allowance rates for 2021 financial year

### PR DESCRIPTION
**Pull request by quis**
These are the new rates from https://docs.google.com/document/d/1aObNQNBw3ayPMl3b_Qc5kZBdaXIAMDnBGtV-xPtFBsc/edit

We’re changing the free allowance so we can continue to support all the teams that use Notify. The new allowance means over 90% of teams can still send all the text messages they need to without paying.

### CODE REVIEW

**Review by idavidmcdonald — COMMENTED** [review]
So this is a tentative approval. So this code all works and is great and well tested.

My only question is this requires us to make a code change every year to keep this working without raising some exceptions. Is that OK? Or after the new financial year do we change this code back to just use a default and not look at the date? Or do we change this code to fall back to something if the key is not found?

**Comment by quis** [comment]
I think we change it back after 1 April, assuming these new allowances continue indefinitely. It’s always possible we change the allowance structure again, but it might change in a way that this logic doesn’t account for (what if we did a per-organisation allowance for example). For me this a quick fix, not a foundation to build on.

**Comment by idavidmcdonald** [comment]
In that case, this is good.

Is changing it back on the 1st of april you will be responsible for or something we need to write a pivotal ticket for?

**Review by idavidmcdonald — APPROVED** [review]

**Comment by quis** [comment]
I’ve added a holding PR for the 1 April change: https://github.com/alphagov/notifications-admin/pull/3830

**Pull request merged**
