### PR TITLE
Embiggen all the things

### PR DESCRIPTION
**Pull request by quis**
Bigger hit areas and font sizes make things easier to click and read.

# Team members

image

image

# Settings

image

image

# Your profile 

image

image

### CODE REVIEW

**Comment by quis** [comment]
@tombye what does the code for the pseudo element technique look like?

**Comment by tombye** [comment]
GOVUK Frontend uses one for their buttons. Sorry, should have posted this with my previous comment:

https://github.com/alphagov/govuk-frontend/blob/47407edcb5694afb36b6aa6b2a6050a5e92f9ef4/src/components/button/_button.scss#L89

**Comment by quis** [comment]
The pseudo-element technique expands the click area without expanding the area of the `:active` state:

image

I prefer expanding the active area too because it helps you understand how big the clickable area is for next time.

This is consistent with how the template navigation works, ie we do this:
image

…not this:
image

**Comment by tombye** [comment]
Maybe I'm missing something but can't that be achieved by including a selector with the `:active` state in it?

I mean like GOVUK Frontend does with the pseudo-element when their button is active:

https://github.com/alphagov/govuk-frontend/blob/47407edcb5694afb36b6aa6b2a6050a5e92f9ef4/src/components/button/_button.scss#L115

**Comment by quis** [comment]
@tombye yeah, that works. Added in 1e82b6f8. It’s more code but if you think that technique is better…

<sup>Also I ended up having to use borders for the active state anyway because a pseudo element can’t underlap it’s parent.</sup>

**Pull request merged**
