### PR TITLE
Guidance for adding an unsubscribe link in the email for API users

### PR DESCRIPTION
**Pull request by saimaghafoor**
Adding guidance for API users to add a link at the bottom of their subscription emails.

### CODE REVIEW

**Comment by quis** [comment]
I don’t think we should add this info here because we risk non-API users trying to follow it. Let’s keep this in the API documentation only

**Comment by saimaghafoor** [comment]
Thanks for the input @quis - it's defo proving to be a tricky one as I can see how it could confuse users. During the API review, it felt like this guidance didn't fit neatly in the API either. The audience for the docs is mostly different to who would actually add/edit templates (and probably need to add this link). @CrystalPea

**Comment by CrystalPea** [comment]
Hey both, it is a tricky one indeed - maybe let's have a chat about it? Only I see we are all very busy with meetings or off... Let me have a think and get back to you both 🙌🏼

**Comment by saimaghafoor** [comment]
Leaving the content as it currently is. No changes needed.

**Pull request closed without merging**
